### ISSUE TITLE
problem with RPly

### ISSUE THREAD

**Issue by OmriTreidel** [c42f/displaz#63] opened 2015-06-30 00:07 UTC
displaz can't load ply files without \n at the end of the file

**Comment by c42f** [comment] 2015-06-30 01:27
I can't reproduce this - I tried taking an ply file from the test directory (eg, test/polygons.ply) and stripping off the last newline but displaz seems to load it fine.  Can you send a small example?

**Comment by c42f** [comment] 2015-06-30 04:39
Fixed in b20c11a ... This was a rather obscure bug in rply itself!  I've also fixed it for you on the triangulate-polygons branch.

**Closed by c42f** 2015-06-30 04:39 UTC

**Comment by OmriTreidel** [comment] 2015-06-30 05:36
Cheers.
